# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3300:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret-password
      MYSQL_DATABASE: accountingdb
      MYSQL_USER: udea
      MYSQL_PASSWORD: secret-password

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080

  account:
    build: ./
    ports:
      - 4000:8080
    depends_on: # El contenedor no iniciará hasta que db nos responda que ya se encuentra disponible
      - db
    links:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db/accountingdb?createIfNotExists=true
      SPRING_DATASOURCE_USERNAME: udea
      SPRING_DATASOURCE_PASSWORD: secret-password
      SPRING_KAFKA_BOOTSTRAP-SERVERS: 172.17.0.1:32769,172.17.0.1:32768

