# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3300:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret-password
      MYSQL_DATABASE: accountingdb
      MYSQL_USER: udea
      MYSQL_PASSWORD: secret-password

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080